CREATE DATABASE IF NOT EXISTS piot_a2;

USE piot_a2;

CREATE TABLE u_user (
    user_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(25) NOT NULL UNIQUE,
    email VARCHAR(255) CHARACTER SET utf8 NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    passwd VARCHAR(255) NOT NULL
);
